### ISSUE TITLE
After downloading I changed index.html but I am not able to see any example what setting required & that need to change by me in my system?

### ISSUE THREAD

**Issue by amitchoubey** [FamousArchives/examples#38]
After downloading I changed index.html but I am not able to see any example what setting required & that need to change by me in my system?

![image](https://cloud.githubusercontent.com/assets/3448322/3053951/97aa0694-e1b1-11e3-8260-8eb1c87db973.png)

Please tell me if any setting is required ?
Tell step by step how can see all examples?

**Comment by michaelobriena** [comment]
As I mentioned in the other thread, you probably do not have git submodules installed.  Try running "git submodule update --init --recursive" from the examples directory.

I am closing this since it is not an issue with the examples repository and should be filed on the repo of the person that built this gallery extension.
